name: lint
on:
  push:
jobs:
  lint:
    strategy:
      matrix:
        go: [1.18, 1.19]
    name: lint
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout"
        uses: actions/checkout@v4
      - name: "Install golang"
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go }}
      - name: "Run go vet"
        run: "go vet ./pkg/..."